[package]
description = "A futures-based websocket implementation"
documentation = "https://docs.rs/futures-websocket"
edition.workspace = true
license = "MIT"
name = "futures-websocket"
repository = "https://github.com/HalaOS/futures.git"
version.workspace = true
